# -*- coding: utf-8 -*-
"""stardist2D_pretrained.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pVE8Y-5e_w5boizq96wZzEvgHTYXV_uI
"""

!pip install stardist

from stardist.models import StarDist2D
from stardist.data import test_image_nuclei_2d
from stardist.plot import render_label
from csbdeep.utils import normalize
import matplotlib.pyplot as plt

StarDist2D.from_pretrained()

model = StarDist2D.from_pretrained('2D_versatile_fluo')

img = plt.imread('/content/stardist_test_2D_EdU.tif')

plt.imshow(img)

labels, _ = model.predict_instances(normalize(img))

plt.subplot(1,2,2)
plt.imshow(render_label(labels, img=img))
plt.axis("off")
plt.title("prediction + input overlay")